In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [112]:
banking_df=pd.read_csv("subscription_prediction.xls")
banking_df["y"]=banking_df["y"].apply(lambda x: 1 if x=="yes" else 0)

In [113]:
banking_df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

Get_dummies is used to make duplicate columns using the values in the columns and make data into boolean

In [114]:
banking_df_c=pd.get_dummies(banking_df,columns=['job','marital','education'])

In [115]:
X=banking_df_c.drop("y",axis=1)
y=banking_df_c["y"]

why validation is important?

We use validation instead of test in the model training coz when we train the model we show the test data to the model that leds to learn the test data will incre accuracy ..that's why we use val instead of test data while training the model ..and after the model trained we check the model through test data that gives the actual accuracy.

In [116]:
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=417)

##val is validation

In [117]:
X_train.shape,X_val.shape

((8097, 41), (2025, 41))

In [118]:
banking_df.shape

(10122, 21)

In [119]:
X_train,X_test,y_train,y_test=train_test_split(X_train,y_train,test_size=0.2*X.shape[0]/X_train.shape[0],random_state=417)

In [120]:
X_train.shape[0],X_val.shape[0],X_test.shape[0]

(6072, 2025, 2025)

In [121]:
from sklearn.neighbors import KNeighborsClassifier

In [122]:
knn=KNeighborsClassifier(n_neighbors=4)

Can't perform one-hot encoding on column month as it is order wise

In [123]:
banking_df_c.select_dtypes("object")

       default housing loan    contact month day_of_week     poutcome
0           no      no   no  telephone   may         mon  nonexistent
1           no      no  yes  telephone   may         mon  nonexistent
2      unknown      no   no  telephone   may         mon  nonexistent
3           no     yes   no  telephone   may         mon  nonexistent
4      unknown      no   no  telephone   may         mon  nonexistent
...        ...     ...  ...        ...   ...         ...          ...
10117       no     yes   no   cellular   nov         fri  nonexistent
10118       no     yes   no   cellular   nov         fri  nonexistent
10119       no     yes   no   cellular   nov         fri  nonexistent
10120       no      no   no   cellular   nov         fri  nonexistent
10121       no     yes   no   cellular   nov         fri      failure

[10122 rows x 7 columns]

Sir will drop all the columns of having dtype object ..so we have to add each column one by one to check the accuracy.

This process is done by cross validation which helps to select the relatable columns for the model which will help to increase the accuracy. also known as feature selection

which methods are in sklearn help in feature selections?

In [124]:
banking_df_c.select_dtypes("object").columns

Index(['default', 'housing', 'loan', 'contact', 'month', 'day_of_week',
       'poutcome'],
      dtype='object')

In [125]:
### knn.fit(X_train,y_train)

##This will create ValueError

'''---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipython-input-60-4084022781.py in <cell line: 0>()
----> 1 knn.fit(X_train,y_train)

12 frames
/usr/local/lib/python3.11/dist-packages/pandas/core/dtypes/astype.py in _astype_nansafe(arr, dtype, copy, skipna)
    131     if copy or arr.dtype == object or dtype == object:
    132         # Explicit copy, or required since NumPy can't view from / to object.
--> 133         return arr.astype(dtype, copy=True)
    134
    135     return arr.astype(dtype, copy=copy)

ValueError: could not convert string to float: 'no'
'''


#As ['default', 'housing', 'loan', 'contact', 'month', 'day_of_week','poutcome'] columns have dtype string/object and we have to either convert into float or drop the columns for model training.

"---------------------------------------------------------------------------\nValueError                                Traceback (most recent call last)\n/tmp/ipython-input-60-4084022781.py in <cell line: 0>()\n----> 1 knn.fit(X_train,y_train)\n\n12 frames\n/usr/local/lib/python3.11/dist-packages/pandas/core/dtypes/astype.py in _astype_nansafe(arr, dtype, copy, skipna)\n    131     if copy or arr.dtype == object or dtype == object:\n    132         # Explicit copy, or required since NumPy can't view from / to object.\n--> 133         return arr.astype(dtype, copy=True)\n    134\n    135     return arr.astype(dtype, copy=copy)\n\nValueError: could not convert string to float: 'no'\n"

In [126]:
X=banking_df_c.drop(['default', 'housing', 'loan', 'contact', 'month', 'day_of_week',
       'poutcome',"y"],axis=1)
y=banking_df_c["y"]

In [127]:
X_train,X_val,y_train,y_val=train_test_split(X,y,test_size=0.2,random_state=417)

In [128]:
X_train.shape,X_val.shape

((8097, 34), (2025, 34))

In [129]:
banking_df.shape

(10122, 21)

In [130]:
X_train,X_test,y_train,y_test=train_test_split(X_train,y_train,test_size=0.2*X.shape[0]/X_train.shape[0],random_state=417)

In [131]:
X_train.shape[0],X_val.shape[0],X_test.shape[0]

(6072, 2025, 2025)

In [132]:
from sklearn.neighbors import KNeighborsClassifier

In [133]:
knn=KNeighborsClassifier(n_neighbors=4)

In [134]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=4)

In [135]:
y_val

7472    0
3408    0
5851    0
9132    1
3790    1
       ..
5828    0
7887    1
2301    0
384     0
8075    1
Name: y, Length: 2025, dtype: int64

In [136]:
pred=knn.predict(X_val)

In [137]:
(y_val==pred).sum()/len(y_val)

np.float64(0.8365432098765432)

In [138]:
knn.score(X_val,y_val)

0.8365432098765432

In [139]:
from sklearn.preprocessing import MinMaxScaler

In [140]:
scaler=MinMaxScaler()

In [141]:
X

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,marital_single,marital_unknown,education_basic.4y,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown
0,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,False,False,False
1,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,False,False,True,False,False,False,False
2,41,217,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,False,False,False,False,False,False,True
3,57,293,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,True,False,False,False,False,False,False,False
4,39,195,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10117,64,151,3,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,False,False,False,False,False,False,False,True,False,False
10118,37,281,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,False,False,False,False,False,False,False,False,True,False
10119,73,334,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,False,False,False,False,False,False,False,True,False,False
10120,44,442,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,False,False,False,False,False,False,False,True,False,False
10121,74,239,3,999,1,-1.1,94.767,-50.8,1.028,4963.6,...,False,False,False,False,False,False,False,True,False,False

In [142]:
X_t=scaler.fit_transform(X)

In [143]:
X_t[0:3]

array([[0.28395062, 0.03596094, 0.        , 1.        , 0.        ,
        0.9375    , 0.69875292, 0.60251046, 0.95737928, 0.85973535,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.48148148, 0.07311265, 0.        , 1.        , 0.        ,
        0.9375    , 0.69875292, 0.60251046, 0.95737928, 0.85973535,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.2962963 , 0.05167897, 0.        , 1.        , 0.        ,
        0.9375    , 0.69875292, 0.60251046, 0.95737928, 0.85973535,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        ]])

here we have learnt that after scaling it is not necessary that it will increase the model accuracy.

So, we will now change the parameters. by changing neighbors to 7-8 , weight will be given and so on.

In [144]:
'''knn=KNeighborsClassifier(n_neighbors=15,metric='minkowski',p=1,weights="distance")'''

'knn=KNeighborsClassifier(n_neighbors=15,metric=\'minkowski\',p=1,weights="distance")'

But it is just hit and trail and it will take a lot of time..so we will learn about grid Search,Overfitting,Underfitting,Evaluation, confusion matrix and so on.

Underfitting- model performing best on test but not good enough on train

Overfitting- model performing best on train but not good enough on test

In [145]:
banking_df_c.columns

Index(['age', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week',
       'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'marital_unknown', 'education_basic.4y', 'education_basic.6y',
       'education_basic.9y', 'education_high.school', 'education_illiterate',
       'education_professional.course', 'education_university.degree',
       'education_unknown'],
      dtype='object')

In [146]:
X

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,...,marital_single,marital_unknown,education_basic.4y,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown
0,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,True,False,False,False,False,False,False
1,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,False,False,True,False,False,False,False
2,41,217,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,False,False,False,False,False,False,False,True
3,57,293,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,False,False,True,False,False,False,False,False,False,False
4,39,195,1,999,0,1.1,93.994,-36.4,4.857,5191.0,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10117,64,151,3,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,False,False,False,False,False,False,False,True,False,False
10118,37,281,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,False,False,False,False,False,False,False,False,True,False
10119,73,334,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,False,False,False,False,False,False,False,True,False,False
10120,44,442,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,...,False,False,False,False,False,False,False,True,False,False
10121,74,239,3,999,1,-1.1,94.767,-50.8,1.028,4963.6,...,False,False,False,False,False,False,False,True,False,False

In [147]:
X.columns

Index(['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'marital_unknown', 'education_basic.4y', 'education_basic.6y',
       'education_basic.9y', 'education_high.school', 'education_illiterate',
       'education_professional.course', 'education_university.degree',
       'education_unknown'],
      dtype='object')

In [148]:
X_t=scaler.fit_transform(X)

In [149]:
X_t[0:3]

array([[0.28395062, 0.03596094, 0.        , 1.        , 0.        ,
        0.9375    , 0.69875292, 0.60251046, 0.95737928, 0.85973535,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.48148148, 0.07311265, 0.        , 1.        , 0.        ,
        0.9375    , 0.69875292, 0.60251046, 0.95737928, 0.85973535,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.2962963 , 0.05167897, 0.        , 1.        , 0.        ,
        0.9375    , 0.69875292, 0.60251046, 0.95737928, 0.85973535,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        ]])

In [150]:
knn.predict_proba(X_val)

array([[1.  , 0.  ],
       [0.5 , 0.5 ],
       [0.75, 0.25],
       ...,
       [0.25, 0.75],
       [1.  , 0.  ],
       [0.25, 0.75]])

In [151]:
banking_df_c.columns

Index(['age', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week',
       'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y',
       'job_admin.', 'job_blue-collar', 'job_entrepreneur', 'job_housemaid',
       'job_management', 'job_retired', 'job_self-employed', 'job_services',
       'job_student', 'job_technician', 'job_unemployed', 'job_unknown',
       'marital_divorced', 'marital_married', 'marital_single',
       'marital_unknown', 'education_basic.4y', 'education_basic.6y',
       'education_basic.9y', 'education_high.school', 'education_illiterate',
       'education_professional.course', 'education_university.degree',
       'education_unknown'],
      dtype='object')

In [152]:
df_1=pd.DataFrame(X_t,columns=X.columns)

In [153]:
df_1["y"]=y

In [154]:
relation=df_1.corr()["y"].sort_values(ascending=False)

In [155]:
relation

y                                1.000000
duration                         0.468197
previous                         0.263903
job_retired                      0.113650
job_student                      0.111979
education_university.degree      0.086403
cons.conf.idx                    0.080425
marital_single                   0.074975
job_admin.                       0.047444
age                              0.046524
education_unknown                0.033031
job_unemployed                   0.029840
education_illiterate             0.015241
job_management                   0.009571
job_unknown                      0.006056
marital_unknown                  0.004070
job_technician                  -0.005098
job_self-employed               -0.005562
education_professional.course   -0.007283
job_housemaid                   -0.008715
marital_divorced                -0.012832
education_high.school           -0.014692
education_basic.4y              -0.016938
job_entrepreneur                -0.025231
education_basic.6y              -0.036933
marital_married                 -0.062697
job_services                    -0.067254
education_basic.9y              -0.076797
campaign                        -0.118361
job_blue-collar                 -0.125771
cons.price.idx                  -0.202009
pdays                           -0.317997
emp.var.rate                    -0.429680
euribor3m                       -0.445328
nr.employed                     -0.468524
Name: y, dtype: float64

In [156]:
a=relation.sort_values(ascending=False)[1:5].index

In [157]:
b=relation.sort_values()[0:5].index

In [158]:
X1=a.append(b)

In [159]:
X_1=banking_df_c[X1]

In [160]:
y1= banking_df_c['y']

In [161]:
X_train,X_val,y_train,y_val=train_test_split(X_1,y1,test_size=0.2,random_state=417)

In [162]:
X_train,X_test,y_train,y_test=train_test_split(X_train,y_train,test_size=0.2*X_1.shape[0]/X_train.shape[0],random_state=417)

In [163]:
X_train.shape[0],X_val.shape[0],X_test.shape[0]

(6072, 2025, 2025)

In [164]:
knn1=KNeighborsClassifier(n_neighbors=7)

In [165]:
knn1.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [166]:
knn1.score(X_val,y_val)

0.851358024691358

Working on non-linear

In [167]:
from sklearn.model_selection import GridSearchCV

In [168]:
grid_param= {"n_neighbors": range(1,7),
             "weights": ["uniform","distance"],
             "metric":["cityblock","euclidean","manhattan"],
             "algorithm":["ball_tree","kd_tree"]}

In [169]:
knn_2=KNeighborsClassifier()

In [170]:
knn_grid=GridSearchCV(knn_2,grid_param,scoring="accuracy")

In [171]:
knn_grid.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree'],
                         'metric': ['cityblock', 'euclidean', 'manhattan'],
                         'n_neighbors': range(1, 7),
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [172]:
knn_grid.best_params_

{'algorithm': 'kd_tree',
 'metric': 'cityblock',
 'n_neighbors': 5,
 'weights': 'uniform'}

In [173]:
knn_grid.best_estimator_

# Make predictions on the test set using the best model

KNeighborsClassifier(algorithm='kd_tree', metric='cityblock')

In [174]:
y_predict= knn_grid.predict(X_val)

In [181]:
knn_grid.score(X_val,y_val)

0.8469135802469135

Taking parameters suggested by Grid Search to make better predict and good acuracy score.

In [205]:
knn3=KNeighborsClassifier(algorithm='ball_tree',metric='euclidean', n_neighbors= 9,weights='uniform')

In [206]:
knn3.fit(X_train,y_train)

KNeighborsClassifier(algorithm='ball_tree', metric='euclidean', n_neighbors=9)

In [207]:
knn3.score(X_val,y_val)

0.8558024691358025

In [208]:
knn3.score(X_test,y_test)

0.8577777777777778